### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by glascaleia** [levelsbeyond/jpoller#6]
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Reach Engine - JPoller 1.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://dev.levelsbeyond.com:8080/nexus/content/repositories/releases/com/levelsbeyond/metamodel-srcgen/1.0.4/metamodel-srcgen-1.0.4.pom
Downloading: http://repo.maven.apache.org/maven2/com/levelsbeyond/metamodel-srcgen/1.0.4/metamodel-srcgen-1.0.4.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.036s
[INFO] Finished at: Thu Feb 20 08:36:47 CET 2014
[INFO] Final Memory: 7M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin com.levelsbeyond:metamodel-srcgen:1.0.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for com.levelsbeyond:metamodel-srcgen:jar:1.0.4: Could not transfer artifact com.levelsbeyond:metamodel-srcgen:pom:1.0.4 from/to lbReleases (http://dev.levelsbeyond.com:8080/nexus/content/repositories/releases): Not authorized , ReasonPhrase:Unauthorized.

**Comment by ericdcobb** [comment]
Thanks- it looks like this was caused by an unnecessary maven plugin that only people inside our organization would have access to. PR should be reviewed and accepted tomorrow morning Colorado time.

**Comment by glascaleia** [comment]
Thanks
